### ISSUE TITLE
The Validation of API Payload does not passes if the optional Fields are of type other than String

### ISSUE THREAD

**Issue by VjSng** [rochacbruno/flasgger#141]
I wrote this in YML file . The validation passes only if there is no optional field (Not required field in the definitions ) of type object or array.

`Create new Deployment Unit
---
tags:
   - Deployment Unit
parameters:
- name: Token
  in: header
  description: API key
  required: true
  type: string
  format: string
- name: input
  in: body
  description: Deployment Unit data
  required: true
  type: string
  format: string
  schema:
    $ref: "#/definitions/DeploymentUnit"     # <---------

responses:
  200:
    description: New Deployment Unit has been added successfully
    schema:
        $ref: "#/definitions/Data"     # <---------
    examples:
      result: "success"
      message: "DeploymentUnit and deployment fields created successfully"
  404:
    description: exception in adding Deployment Unit
    examples:
      result: "failed"
      message: "Throws an exception"

definitions:
  DeploymentUnit:           # <----------
    type: object
    required:
      - name 
      - type
    properties:
      name:
        type: string 
      type:
        type: string
      release_notes:
        type: string
      branch:
        type: string 
      approval_status:
        type: string
      approval_list:
        type: array
        items:
          type: object
          properties:
            approval_status:
              type: string
            approved_by:
              type: string
            approved_date:
              type: string

   
     
  Data:
    type: object
    properties:
        data:
          type: string
        result:
          type: string
        message:
           type: string
`

**Comment by VjSng** [comment]
@rochacbruno . can you please provide some resolution ?

**Comment by allrod5** [comment]
I haven't tried to reproduce your error yet, but `items` seems to be lacking proper schema definition:

```yaml
      approval_list:
        type: array
        items:
          type: object
          schema:
            id: ApprovalListItem
            properties:
              approval_status:
                type: string
              approved_by:
                type: string
              approved_date:
                type: string
```
