### ISSUE TITLE
does not support upload

### ISSUE THREAD

**Issue by yumen** [rochacbruno/flasgger#168]
"""
    test
    ---
    tags:
      - test
    parameters:
      - in: file
        name: formData
        
        type: file
        required: true    
        
    responses:
      200:
        description:
    """
my yaml is this,I find it can upload succ,need you help and can give me a upload example,thanks very much.

**Comment by ongopongo** [comment]
File uploads are working for me.

Here's the relevant part of my Flasgger YAML snippet in my function docstring:

```yaml
    Upload a file.
    ---
    tags: [SomeTag]
    consumes: [multipart/form-data]
    parameters:
        - name: file
          in: formData
          required: true
          type: file
          description: The file you want to store
```

As a result, the Swagger UI shows a file upload field.

![image](https://user-images.githubusercontent.com/53710895/78607592-3a3d5b00-7814-11ea-95ec-5bf889883662.png)
