### ISSUE TITLE
How to fetch next result "idStatus=1&idStatus=3"

### ISSUE THREAD

**Issue by Kvasela** [rochacbruno/flasgger#176]
I have next yml file

```
Return list of foo
---
tags:
- "Foo"
summary: "Return list of foo"
description: ""

produces:
- "application/json"

parameters:
- in: "query"
  name: "limit"
  type: "integer"
  description: ""
  default: 10

- in: "query"
  name: "page"
  type: "integer"
  description: ""
  default: 1

- in: "query"
  name: "idStatus"
  description: ""
  type: "array"
  items:
    type: "integer"
  style: "form"
  explode: true
```
