### ISSUE TITLE
How to let maximum constraint work in swagger ui and also could validate it in server?

### ISSUE THREAD

**Issue by zhugw** [rochacbruno/flasgger#254]
**Requirements**
I want to let user cannot input a number parameter not greater than a specific value in swagger ui
and also server-end could validate the input parameter
**Problem** 
I tried below manners all not work so how to implement it?  

why maximum constraint not work in swagger-ui?

```
  - name: limit
    in: formData
    type: integer
    required: true
    maximum: 50000
    description: total count max 50000
```
the `maximum` constraint not work in swagger ui still could set value more than 50000 and try it out
![image](https://user-images.githubusercontent.com/4953871/46912283-ba7a5b80-cfa3-11e8-8b91-b0d8f0ea730e.png)

So then explicitly validate the form data by specifying `validation=True`

```
@swag_from('data_download.yml', validation=True) 
```
but in this case I only  got below result
```
Status Code: 500 INTERNAL SERVER ERROR
Response: No data to validate
```

So how to let flasgger could validate the form data successfully? Below is detailed yml config

```
produces:
  - application/octet-stream
parameters:
  - name: tableName
    in: formData
    type: string
    required: true
    description: table name
  - name: limit
    in: formData
    type: integer
    required: true
    maximum: 50000
    description: total count max 50000
  - name: start
    in: formData
    type: string
    required: true
    description: start date yyyy-MM-dd
  - name: end
    in: formData
    type: string
    required: true
    description: end date yyyy-MM-dd
```
