### ISSUE TITLE
Array type not allowed in JSON body POST

### ISSUE THREAD

**Issue by harpalsahota** [rochacbruno/flasgger#274]
I have the following schema for a post request with a JSON body:

```
parameters:
    - in: body
      name: body
      required: true
      schema:
        type: object
        properties:
          xa:
            type: array
            minItems: 1
            items:
              type: array
              minItems: 1
              items:
                type: number
```
As you can see `xa` is of type `array`. Going to `/apidocs` everything works fine but when attempting to to run the example or post the endpoint with a JSON I receive the following error: 
```
KeyError: 'array'
```
in `base.py, line 584, in before_request`.

Looks like it is referencing `SCHEMA_TYPES` in `base.py` which is defined as follows:
```
SCHEMA_TYPES = {'string': str, 'integer': int, 'number': 'boolean': bool, 'object': dict}
```
No schema type of array is present? any idea why?
