### ISSUE TITLE
Validate is not working: unknown url type

### ISSUE THREAD

**Issue by isaacfi** [rochacbruno/flasgger#311]
I've tried to use an external yml file to specify the body post parameter User.

The login operation schema is this:

**/schemas/security/login.yml**:
```
Init user session
User to get token
---
id: login
tags:
  - seguridad
operationId: login
parameters:
  - in: body
    name: User
    description: User
    required: true
    schema:
      $ref: '#/definitions/User'
responses:
  '200':
    description: Authenticated user
    schema:
      $ref: '#/definitions/User'
definitions:
  User:
    $ref: '/schemas/security/user.schema.yml'
```

The referenced user.schema.yml is this:

**/schemas/security/user.schema.yml**:
```
User
---
id: User
required:
  - _key
  - email
  - name
  - userType
  - authType
properties:
  _key:
    type: string
    uniqueItems: true
    description: User Id
  email:
    type: string
    format: email
    description: E-mail
  name:
    type: string
    description: Name
  lastName:
    type: string
    description: Last name
  mobile:
    type: string
    description: Mobile number
  userType:
    type: string
    description: User type
  authType:
    type: string
    description: Authentication type
  socialToken:
    type: string
    description: Social token
  creationDate:
    type: string
    format: date-time
    description: User creation date
  lastLogin:
    type: string
    format: date-time
    description: User last login
```

And in the blueprint called user_controller:

```
from json import dumps, loads
from flask import Blueprint, Response, request, current_app
from flasgger import swag_from, validate
import sys
import os

main = Blueprint('user_controller', __name__)

yml_login_path = os.path.join(os.path.dirname(
    sys.argv[0]), 'schemas', 'security', 'login.yml')

@main.route('/security/login', methods=['POST'])
@swag_from(yml_login_path, validation=True)
def login():
    return Response(dumps({'access_token': 'testToken'}), mimetype='application/json', status=200)
```

The swagger site is showing good, but if I activate the validation=True at the method, I got this error:

Http error: 400
Message: unknown url type: '/schemas/security/user.schema.yml'
